# ---------------------------------------------------------------------------------------------
# Provisions an EFS using the specified VPC, Subnets and Security Group (they must belong to
# the same VPC). Also adds ingress rule for VPC CIDR (IPv4 and/or IPv6) TCP port 2049. This
# is intended to be used to create an EFS that can be shared by all hosts within the VPC
# ---------------------------------------------------------------------------------------------
AWSTemplateFormatVersion: 2010-09-09
Description: Hosts EFS

Parameters:
  VPCIP4CIDR:
    Type: String
    Description: The VPC IPv4 CIDR

  VPCIP6CIDR:
    Type: String
    Description: The VPC IPv6 CIDR

  SubnetID1:
    Type: AWS::EC2::Subnet::Id
    Description: Mount target 1 subnet ID

  SubnetID2:
    Type: AWS::EC2::Subnet::Id
    Description: Mount target 2 subnet ID

  SubnetID3:
    Type: AWS::EC2::Subnet::Id
    Description: Mount target 3 subnet ID

  SecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for mount targets

Conditions:
  CreateIPV4Ingress: !Not [!Equals [!Ref VPCIP4CIDR, ""]]
  CreateIPV6Ingress: !Not [!Equals [!Ref VPCIP6CIDR, ""]]

Resources:

  FileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      BackupPolicy:
        Status: DISABLED
      PerformanceMode: generalPurpose
      Encrypted: false
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
      FileSystemTags:
        - Key: Name
          Value: hosts-filesystem
#      FileSystemPolicy:
#        Version: "2012-10-17"
#        Statement:
#          - Effect: "Allow"
#            Action:
#              - "elasticfilesystem:ClientMount"
#            Principal:
#              AWS: '*'
#            Condition:
#              StringEquals:
#                'aws:PrincipalOrgID': o-dhb7rpaban

  MountTargetResource1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref SubnetID1
      SecurityGroups:
        - !Ref SecurityGroupID

  MountTargetResource2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref SubnetID2
      SecurityGroups:
        - !Ref SecurityGroupID

  MountTargetResource3:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref SubnetID3
      SecurityGroups:
        - !Ref SecurityGroupID

  SecurityGroupIngressIP4:
    Condition: CreateIPV4Ingress
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: !Ref VPCIP4CIDR
      GroupId: !Ref SecurityGroupID
      Description: "EFS for VPC"
      FromPort: 2049
      IpProtocol: "tcp"
      ToPort: 2049

  SecurityGroupIngressIP6:
    Condition: CreateIPV6Ingress
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIpv6: !Ref VPCIP6CIDR
      GroupId: !Ref SecurityGroupID
      Description: "EFS for VPC"
      FromPort: 2049
      IpProtocol: "tcp"
      ToPort: 2049
